language: node_js

node_js:
  - stable

git:
  depth: 10

addons:
  firefox: "41.0.1"
  sauce_connect: true

script: npm run $COMMAND

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

env:
  global:
    - secure: "G1qQhww+f9uQmmXGEyUEEip/wged9mkkAtg4IoywuGP9wo0mSkSiIOJ8i1o9H2RCV2YNBBwt0RbaI6g1N5QvhWt9hbm99rQZCgAW2loTLPDtod4FaM07gc7SlrlLwKkSe1v6+b3fO4BmwLk7C1dYMLek1aGaWNEEGXjUpuNuw3JN4+BzNtLbWEnKqUS9bhEdrmoRXk+nuQiR26Tg02ZcuGTMAVSAWvvzBdZacN8Tu/Tveq6MUay/P6CBE8ovoHUAyXio++0mbWZubq9zC6DvSMAMCe0tbUGKar1dtH7jWQnC1gW40SUcDunBkdjFts297JbdeXj+IEv/Sd869Un3c6zjmFY4w65LCAb9QDYVOxZU+1lVvTRyR5oQ7rA6mS815YcgNGdqSZMdhZxGvmJyiSaSHSG7emWkz75Xt5ZHE6H7J79JAaxT3DHLWeTVwr1excJum3H5i2SPCv3nBPI+o6zSif+6oqU+VbPoFIoFhAkjtrP2qPB0WFteDUaX1NpBRe0MgaZeiwcQPxMx4+L1TOotO93Ecyy0Ch2ALc60sYK3fjEFEnsN/6aS4K5Awcoi05VYnif3aTaFHOvuyt5sfydeM8KyQEqvnbowSsHpsb0oWU3cmVpooxeuO85mQFgeZJnSt2YpncDSC348tBja5J1DM24wA7RT7lXtbGW4B2E="
    - secure: "NNcrDHNrO34CMJLOqDhs35rtj1ddOsBPQ+gN9VZZQnU+9v3CjOKB6MXNmNLDpupz3MTTwYa4dGOA37cjqKA1lE9v4pGaAyi6Xm8QWR8ZxFrFXli5oPfqLK/sLEsdHMvoenEucckZ0NshkTqatK+lrl/n8y06fWCvl+diIMxlvaWDb7tVVYZW97OmPCic8XoHU9VNAdOOshu6jjJQVKgGJ3ldX02/VcVtIT5ld0p2ipnPn5RTQzFu4YsGPR+tX4lJr9mDHyS8OtYabuPnad2npymUKddnGZmSEFe/3J1SxGeJWmNr4iJerC8bWWxw6NFNOvXElfqQOU0R99NbfMVpw+O2WnJg3pM9JR2QDn/gGXZHAEHYc9o4FJluJnxEpYY7hLqs/2fPkAFTDWflkMMnAJnWX/lO42/YO/rC1Z87OT0eWgQ+i6N/W8rHJyQGqRKS5JTf8s3MJGM2835DItyKihEeLxpqibtRj5EszhN0vWqKBRCf2L5JX58yp8JUQcm5sAjElfuNaWKClf4oK3FqmzhDGSojK2Tnv3eZkLwqEqAwwzDwGUMiqre00YGXT+Rn135b8Wp2az5yb1HcPNmS97UuKH6y+Ok4CL13pw+W6KuhCRcxY0VqVUMXw7cWjE4GGNYXwbStZnpnb3AYerf9rzBWidHd22uVhGCfBQIwIpY="

  matrix:
    - BROWSER=firefox COMMAND=test
    - COMMAND=test-fakeindexeddb
    - COMMAND=test-phantom
    - COMMAND=test-saucelabs BROWSER_NAME=iphone BROWSER_VERSION="8.0..latest"
    - COMMAND=test-saucelabs BROWSER_NAME=safari BROWSER_VERSION="7..latest"
    - COMMAND=test-saucelabs BROWSER_NAME=android BROWSER_VERSION="4.4..latest"
    - COMMAND=test-saucelabs BROWSER_NAME=ie BROWSER_VERSION="10..latest"
    - COMMAND=test-saucelabs BROWSER_NAME=firefox BROWSER_VERSION="38..latest"
    - COMMAND=test-saucelabs BROWSER_NAME=chrome BROWSER_VERSION="42..beta"
branches:
  only:
  - master
